// <auto-generated />
using System;
using System.Collections.Generic;
using FitnessApp.Nutrition.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitnessApp.Nutrition.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NutritionDbContext))]
    partial class NutritionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitnessApp.Nutrition.Domain.Entities.DailyTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("Goal")
                        .HasColumnType("integer")
                        .HasColumnName("Goal");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DailyTargets", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Nutrition.Domain.Entities.MealLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LoggedAt");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("MealName");

                    b.Property<int>("MealType")
                        .HasColumnType("integer")
                        .HasColumnName("MealType");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LoggedAt");

                    b.ToTable("MealLogs", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Nutrition.Domain.Entities.MealPlanTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("MealPlanTemplates", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Nutrition.Domain.Entities.TemplateMeal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Description");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("DishName");

                    b.Property<int>("MealType")
                        .HasColumnType("integer")
                        .HasColumnName("MealType");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("TemplateId");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("TemplateMeals", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Nutrition.Domain.Entities.UserTemplateQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("LastResetAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastResetAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.Property<IReadOnlyCollection<Guid>>("ViewedTemplateIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ViewedTemplateIds");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserTemplateQueues", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Nutrition.Domain.Entities.WeightLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LoggedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.Property<float>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("real")
                        .HasColumnName("Weight");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LoggedAt");

                    b.ToTable("WeightLogs", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Nutrition.Domain.Entities.DailyTarget", b =>
                {
                    b.OwnsOne("FitnessApp.Nutrition.Domain.ValueObjects.NutritionValue", "Target", b1 =>
                        {
                            b1.Property<Guid>("DailyTargetId")
                                .HasColumnType("uuid");

                            b1.Property<float>("Calories")
                                .HasPrecision(8, 2)
                                .HasColumnType("real")
                                .HasColumnName("TargetCalories");

                            b1.Property<float>("Carbs")
                                .HasPrecision(8, 2)
                                .HasColumnType("real")
                                .HasColumnName("TargetCarbs");

                            b1.Property<float>("Fats")
                                .HasPrecision(8, 2)
                                .HasColumnType("real")
                                .HasColumnName("TargetFats");

                            b1.Property<float>("Proteins")
                                .HasPrecision(8, 2)
                                .HasColumnType("real")
                                .HasColumnName("TargetProteins");

                            b1.HasKey("DailyTargetId");

                            b1.ToTable("DailyTargets");

                            b1.WithOwner()
                                .HasForeignKey("DailyTargetId");
                        });

                    b.Navigation("Target")
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessApp.Nutrition.Domain.Entities.MealLog", b =>
                {
                    b.OwnsOne("FitnessApp.Nutrition.Domain.ValueObjects.NutritionValue", "Nutrition", b1 =>
                        {
                            b1.Property<Guid>("MealLogId")
                                .HasColumnType("uuid");

                            b1.Property<float>("Calories")
                                .HasPrecision(8, 2)
                                .HasColumnType("real")
                                .HasColumnName("Calories");

                            b1.Property<float>("Carbs")
                                .HasPrecision(8, 2)
                                .HasColumnType("real")
                                .HasColumnName("Carbs");

                            b1.Property<float>("Fats")
                                .HasPrecision(8, 2)
                                .HasColumnType("real")
                                .HasColumnName("Fats");

                            b1.Property<float>("Proteins")
                                .HasPrecision(8, 2)
                                .HasColumnType("real")
                                .HasColumnName("Proteins");

                            b1.HasKey("MealLogId");

                            b1.ToTable("MealLogs");

                            b1.WithOwner()
                                .HasForeignKey("MealLogId");
                        });

                    b.Navigation("Nutrition")
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessApp.Nutrition.Domain.Entities.MealPlanTemplate", b =>
                {
                    b.OwnsOne("FitnessApp.Nutrition.Domain.ValueObjects.NutritionValue", "TotalNutrition", b1 =>
                        {
                            b1.Property<Guid>("MealPlanTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<float>("Calories")
                                .HasPrecision(8, 2)
                                .HasColumnType("real")
                                .HasColumnName("TotalCalories");

                            b1.Property<float>("Carbs")
                                .HasPrecision(8, 2)
                                .HasColumnType("real")
                                .HasColumnName("TotalCarbs");

                            b1.Property<float>("Fats")
                                .HasPrecision(8, 2)
                                .HasColumnType("real")
                                .HasColumnName("TotalFats");

                            b1.Property<float>("Proteins")
                                .HasPrecision(8, 2)
                                .HasColumnType("real")
                                .HasColumnName("TotalProteins");

                            b1.HasKey("MealPlanTemplateId");

                            b1.ToTable("MealPlanTemplates");

                            b1.WithOwner()
                                .HasForeignKey("MealPlanTemplateId");
                        });

                    b.Navigation("TotalNutrition")
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessApp.Nutrition.Domain.Entities.TemplateMeal", b =>
                {
                    b.HasOne("FitnessApp.Nutrition.Domain.Entities.MealPlanTemplate", "Template")
                        .WithMany("Meals")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FitnessApp.Nutrition.Domain.ValueObjects.NutritionValue", "Nutrition", b1 =>
                        {
                            b1.Property<Guid>("TemplateMealId")
                                .HasColumnType("uuid");

                            b1.Property<float>("Calories")
                                .HasPrecision(8, 2)
                                .HasColumnType("real")
                                .HasColumnName("Calories");

                            b1.Property<float>("Carbs")
                                .HasPrecision(8, 2)
                                .HasColumnType("real")
                                .HasColumnName("Carbs");

                            b1.Property<float>("Fats")
                                .HasPrecision(8, 2)
                                .HasColumnType("real")
                                .HasColumnName("Fats");

                            b1.Property<float>("Proteins")
                                .HasPrecision(8, 2)
                                .HasColumnType("real")
                                .HasColumnName("Proteins");

                            b1.HasKey("TemplateMealId");

                            b1.ToTable("TemplateMeals");

                            b1.WithOwner()
                                .HasForeignKey("TemplateMealId");
                        });

                    b.Navigation("Nutrition")
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("FitnessApp.Nutrition.Domain.Entities.MealPlanTemplate", b =>
                {
                    b.Navigation("Meals");
                });
#pragma warning restore 612, 618
        }
    }
}
