// <auto-generated />
using System;
using FitnessApp.Workout.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitnessApp.Workout.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitnessApp.Workout.Domain.Entities.TrainingDay", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("TrainingProgramId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrainingProgramId");

                    b.ToTable("TrainingDays", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Workout.Domain.Entities.TrainingProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedOn");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("TrainingPrograms", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Workout.Domain.Entities.WorkoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedOn");

                    b.Property<Guid>("TrainingDayId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("WorkoutSessions", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Workout.Domain.Entities.TrainingDay", b =>
                {
                    b.HasOne("FitnessApp.Workout.Domain.Entities.TrainingProgram", "TrainingProgram")
                        .WithMany("TrainingDays")
                        .HasForeignKey("TrainingProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("FitnessApp.Workout.Domain.ValueObjects.ExerciseSet", "Exercises", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<int>("ExerciseType")
                                .HasColumnType("integer");

                            b1.Property<int>("Reps")
                                .HasColumnType("integer");

                            b1.Property<int>("Sets")
                                .HasColumnType("integer");

                            b1.Property<Guid>("TrainingDayId")
                                .HasColumnType("uuid");

                            b1.Property<float>("Weight")
                                .HasPrecision(5, 2)
                                .HasColumnType("real");

                            b1.HasKey("Id");

                            b1.HasIndex("TrainingDayId");

                            b1.ToTable("PlannedExercises", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TrainingDayId");
                        });

                    b.Navigation("Exercises");

                    b.Navigation("TrainingProgram");
                });

            modelBuilder.Entity("FitnessApp.Workout.Domain.Entities.TrainingProgram", b =>
                {
                    b.OwnsOne("FitnessApp.Workout.Domain.ValueObjects.ProgramProfile", "ProgramProfile", b1 =>
                        {
                            b1.Property<Guid>("TrainingProgramId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Goal")
                                .HasColumnType("integer")
                                .HasColumnName("Goal");

                            b1.Property<int>("Intensity")
                                .HasColumnType("integer")
                                .HasColumnName("Intensity");

                            b1.HasKey("TrainingProgramId");

                            b1.ToTable("TrainingPrograms");

                            b1.WithOwner()
                                .HasForeignKey("TrainingProgramId");

                            b1.OwnsOne("FitnessApp.Workout.Domain.ValueObjects.PowerMetrics", "PowerMetrics", b2 =>
                                {
                                    b2.Property<Guid>("ProgramProfileTrainingProgramId")
                                        .HasColumnType("uuid");

                                    b2.Property<float>("BenchPressWeight")
                                        .HasPrecision(5, 2)
                                        .HasColumnType("real")
                                        .HasColumnName("PowerMetrics_BenchPressWeight");

                                    b2.Property<float>("DeadliftWeight")
                                        .HasPrecision(5, 2)
                                        .HasColumnType("real")
                                        .HasColumnName("PowerMetrics_DeadliftWeight");

                                    b2.Property<float>("SquatWeight")
                                        .HasPrecision(5, 2)
                                        .HasColumnType("real")
                                        .HasColumnName("PowerMetrics_SquatWeight");

                                    b2.HasKey("ProgramProfileTrainingProgramId");

                                    b2.ToTable("TrainingPrograms");

                                    b2.WithOwner()
                                        .HasForeignKey("ProgramProfileTrainingProgramId");
                                });

                            b1.Navigation("PowerMetrics");
                        });

                    b.Navigation("ProgramProfile")
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessApp.Workout.Domain.Entities.WorkoutSession", b =>
                {
                    b.OwnsMany("FitnessApp.Workout.Domain.ValueObjects.ExerciseSet", "PerformedExercises", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<int>("ExerciseType")
                                .HasColumnType("integer");

                            b1.Property<int>("Reps")
                                .HasColumnType("integer");

                            b1.Property<int>("Sets")
                                .HasColumnType("integer");

                            b1.Property<float>("Weight")
                                .HasPrecision(5, 2)
                                .HasColumnType("real");

                            b1.Property<Guid>("WorkoutSessionId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("WorkoutSessionId");

                            b1.ToTable("PerformedExercises", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkoutSessionId");
                        });

                    b.Navigation("PerformedExercises");
                });

            modelBuilder.Entity("FitnessApp.Workout.Domain.Entities.TrainingProgram", b =>
                {
                    b.Navigation("TrainingDays");
                });
#pragma warning restore 612, 618
        }
    }
}
